[workspace]
members = ["procmacros", "recess"]
resolver = "2"

[workspace.package]
repository = "https://github.com/PurityLake/recess"
authors = ["Robert O'Shea"]
license = "GNU-GPL3"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
